### ISSUE TITLE
[FEATURE] Built-in support for loading avro files

### ISSUE THREAD

**Issue by kvnkho** [fugue-project/fugue#125]
Spark has support for reading in avro files.

Pandas will be a bit trickier. We'll need to add `fastavro` as a dependency. Sample script for how to read avro into pandas:
https://gist.github.com/LouisAmon/300b4a906a6d25a7fb5d2c4d174d242e

Place to add functionality.
https://github.com/fugue-project/fugue/blob/master/fugue/_utils/io.py

**Comment by gityow** [comment]
I'll take this! :)
