### ISSUE TITLE
[BUG] The README code does not immediately work

### ISSUE THREAD

**Issue by kvnkho** [fugue-project/fugue#132]
**Minimal Code To Reproduce**

```python
from typing import Iterable, Dict, Any, List

# Creating sample data
data = [
    ["A", "2020-01-01", 10],
    ["A", "2020-01-02", None],
    ["A", "2020-01-03", 30],
    ["B", "2020-01-01", 20],
    ["B", "2020-01-02", None],
    ["B", "2020-01-03", 40]
]
schema = "id:str,date:date,value:int"

# schema: *, filled:int
def fillna(df:Iterable[Dict[str,Any]],value:int=0) -> Iterable[Dict[str,Any]]:
    for row in df:
        for col in cols:
            row["filled"] = (row["value"] or value)
        yield row

with FugueWorkflow() as dag:
    df1 = dag.df(data, schema).transform(fillna)
    df1.show()
```

**Describe the bug**
1. FugueWorkflow needs to be imported
2. Int will have problems on Dask because it can't hold None. Change the type to double

**Expected behavior**
It should work out of the box. All other code in the README should work as well so just run the code and make sure everything works.

**Environment (please complete the following information):**
 - Backend: All engines
 - Backend version: 0.4.9
 - Python version: 3.7
 - OS: linux/windows: Both

**Comment by kvnkho** [comment]
Please remove emojis from README with this item. They don't render well on [PyPi](https://pypi.org/project/fugue/)

**Comment by gityow** [comment]
I'll work on this!
