### ISSUE TITLE
[BUG] Jinja templating for FugueSQL is failing with string

### ISSUE THREAD

**Issue by kvnkho** [fugue-project/fugue#134]
**Minimal Code To Reproduce**

```python
from fugue_sql import FugueSQLWorkflow
data = [
    ["A", "2020-01-01", 10],
    ["A", "2020-01-02", None],
    ["A", "2020-01-03", 30],
    ["B", "2020-01-01", 20],
    ["B", "2020-01-02", None],
    ["B", "2020-01-03", 40]
]
schema = "id:str,date:date,value:double"

with FugueSQLWorkflow() as dag:
    df = dag.df(data, schema)
    x = "A"
    dag("""
        SELECT *
          FROM df
         WHERE id = {{x}}
         PRINT
    """)
```

**Describe the bug**
Inserting numeric variables work but string variables does not. 

**Expected behavior**
It should work 

**Environment (please complete the following information):**
 - Backend: Pandas and Dask
 - Backend version: Fugue 0.4.9
 - Python version: 3.7
 - OS: linux/windows: Linux

**Comment by kvnkho** [comment]
This old PR might be a good starting point. 
https://github.com/fugue-project/fugue/pull/85

**Comment by gityow** [comment]
Thanks, I'll work on this.

**Comment by kvnkho** [comment]
Talked to @gityow  about this, the difficulty is that sometimes the string variable refers to a column name or table. Sometimes the string variable is used in a `WHERE` clause. The first case requires no quotation marks. The second case requires quotation marks. It will be very hard to identify a user's intention so this should probably be explicitly specified by the user.

It looks like we're converging to Jinja filters. The built-in filter [to_json](https://jinja.palletsprojects.com/en/2.11.x/templates/#tojson) inserts quotes around the variable. The behavior is nice but the name is weird for our use case. Making a custom filter is a possibility. This would be used as follows:

```python
with FugueSQLWorkflow() as dag:
    df = dag.df(data, schema)
    x = "A"
    dag("""
        SELECT *
          FROM df
         WHERE id = {{x | custom_filter}}
         PRINT
    """)
```
