### ISSUE TITLE
[BUG] Javascript Error: require is not defined (Jupyterlab 3.0.15)

### ISSUE THREAD

**Issue by pybokeh** [fugue-project/fugue#223]
Hello, I am just going through the tutorial.

I have done the following to install and setup Fugue:
```
pip install fugue[sql,dask]
jupyter nbextension install --py fugue_notebook
jupyter nbextension enable fugue_notebook --py
```

In Jupyter Lab environment, when I execute the following in a code cell:
```
from fugue_notebook import setup
setup ()
```
I then get the following in the output cell: `Javascript Error: require is not defined`

Otherwise, everything else seems to be working correctly.

OS: Windows 10
Browser: Chrome version 91.0.4472.101
Python version: 3.8.10
Fugue version: 0.5.6
Jupyterlab version: 3.0.15
Jupyterlab-widgets version: 1.0.0
ipywidgets version: 7.6.3
notebook version: 6.4.0

Output of running `jupyter nbextension list` command at terminal:
```
Known nbextensions:
  config dir: C:\Users\<some_user>\.jupyter\nbconfig
    notebook section
      fugue_notebook/main enabled
      - Validating: ok
  config dir: c:\users\<some_user>\apps\python38\envs\jupyterlab_dev\etc\jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
```

**Comment by pybokeh** [comment]
Closing as I discovered this error message is related to the lack of syntax highlight support with jupyterlab.

**Comment by goodwanghan** [comment]
In lab, you must set `is_lab` to True to not initializing javascript. We haven't be able to enable highlighting for lab notebooks. We only support classic notebooks highlighting.

https://github.com/fugue-project/fugue/blob/f1ff762327b13f062cdef676e9df84fc9c4ce1a6/fugue_notebook/__init__.py#L61
