### ISSUE TITLE
[FEATURE] Windows OS Support

### ISSUE THREAD

**Issue by pybokeh** [fugue-project/fugue#224]
Performing the tutorial on Input and Outputs, the examples using LOAD and SAVE statements do not seem to work on Windows file system:

```
%%fsql
CREATE [[0,"1"]] SCHEMA a:int,b:str
SAVE OVERWRITE "/tmp/f.csv" (header=true)
```

I've tried full path with forward slash:
`SAVE OVERWRITE "C:/some_folder/f.csv" (header=true)`

or double backward slashes:
`SAVE OVERWRITE "C:\\some_folder\\f.csv" (header=true)`

Although I can use WSL/WSL2, others in my organization are not able to install WSL/WSL2 without admin/elevated privileges on their machine.

**Comment by goodwanghan** [comment]
Agree, we have not made windows path work. We should make it work.

I am curious if you are also using a centralized file system such as s3 or hdfs?

**Comment by pybokeh** [comment]
Hi @goodwanghan , I do have access to PySpark environment to access s3 buckets.

**Comment by goodwanghan** [comment]
Sounds good, I will see how to make windows path work @pybokeh

**Comment by goodwanghan** [comment]
I am working on this. We need to update triad package first to make it support windows.

Meanwhile, you could try it on s3. You will need the package https://pypi.org/project/fs-s3fs/ to support s3 paths. Fugue has been used extensively on s3, so you may give a try.

**Comment by goodwanghan** [comment]
The major change will be in triad https://github.com/fugue-project/triad/pull/69
We have made triad fully compatible with windows. Future release will pass both windows and linux tests

**Comment by goodwanghan** [comment]
`0.6.0.dev2` should be released in a few minutes. 

You should be able to use either `"C:/some_folder/f.csv"` or "C:\\some_folder\\f.csv" for non-spark engines. For pyspark on windows, I haven't been able to setup an environment like that, so I was not able to test. If you can help test and that will be great.

**Comment by pybokeh** [comment]
@goodwanghan Thank you!  Look forward to the 0.6.0 release.  I was able to test the 0.6.0.dev2 version with Windows file system / non-pyspark environment and things are working as expected.  Also, just wanted to clarify, I'm pretty sure you meant "C:\\\some_folder\\\f.csv" as GH markdown syntax require 3 back slashes to render 2 back slashes.  Not sure if I'll be able to test with pyspark on Windows as I had difficulty trying to setup such an environment myself.  Our current pyspark environment is on containerization platform.

**Comment by goodwanghan** [comment]
> @goodwanghan Thank you! Look forward to the 0.6.0 release. I was able to test the 0.6.0.dev2 version with Windows file system / non-pyspark environment and things are working as expected. Also, just wanted to clarify, I'm pretty sure you meant "C:\\some_folder\\f.csv" as GH markdown syntax require 3 back slashes to render 2 back slashes. Not sure if I'll be able to test with pyspark on Windows as I had difficulty trying to setup such an environment myself. Our current pyspark environment is on containerization platform.

Yes, sorry that was my typo in the reply.
