### ISSUE TITLE
[FEATURE] Add fugue to conda-forge

### ISSUE THREAD

**Issue by rdmolony** [fugue-project/fugue#242]
**Is your feature request related to a problem? Please describe.**
fugue isn't available on conda yet, packages with non-python dependencies are usually more easily installed via conda

**Describe the solution you'd like**
`conda install fugue -c conda-forge`

---

The following dependencies need to be added to anaconda (conda-forge requires all dependencies be on the conda-forge channel) to make this possible:

- [x] adagio: [github](https://github.com/fugue-project/adagio), dependencies: only triad not on anaconda
- [ ] qpd: [pypi](https://pypi.org/project/qpd/), dependencies: only triad not on anaconda (the hompage link to the github is broken so found by extracting setup.py from the tar.gz file)
- [x] [triad](https://github.com/fugue-project/triad) - all dependencies on anaconda

I added a package (ploomber) to conda-forge, and am happy to do the same for fugue

---

Additional tasks:

- [ ] (optional) Update fugue Makefile `make setupinconda` for conda-forge install
- [ ] (Optional) Add an environment.yml for local development
- [ ] Update README with conda badges
- [ ] Open source qpd (conda-forge requires a LICENSE)

**Comment by goodwanghan** [comment]
That will be fantastic!!

@rdmolony can you join the [slack channel](https://join.slack.com/t/fugue-project/shared_invite/zt-jl0pcahu-KdlSOgi~fP50TZWmNxdWYQ) let's chat about the details? I started a little bit on the conda side long time ago, it would be great if you can drive this.

**Comment by rdmolony** [comment]
No problem @goodwanghan :)

**Comment by kvnkho** [comment]
You might as well edit this Makefile of this repo to support installing with `conda` also when you finish. If you're willing of course.

**Comment by rdmolony** [comment]
Happy to Kevin, please feel free to add any tasks you can think of to the list above

**Comment by kvnkho** [comment]
Actually, I realized `makeinconda` is for the installation of a development environment. We probably just want to update the README as you have above.

**Comment by rdmolony** [comment]
- Ref conda-forge/staged-recipes#16044
- Ref conda-forge/staged-recipes#16099

**Comment by kvnkho** [comment]
This got done. We are on conda-forge: https://anaconda.org/conda-forge/fugue
