### ISSUE TITLE
[BUG] ArrayType of structType isn't supported in spark sql 

### ISSUE THREAD

**Issue by WangCHX** [fugue-project/fugue#308]
**Minimal Code To Reproduce**

```sql
SELECT array type of nest struct type FROM some_table
```

**Describe the bug**
```
TypeError: Unsupported type in conversion to Arrow: ArrayType(StructType(List(StructField(some_columne,StringType,true))))
```

**Expected behavior**
The query should work.

**Environment (please complete the following information):**
 - Backend: spark
 - Backend version: 3.1.2
 - Python version: 3.8
 - OS: linux

**Comment by goodwanghan** [comment]
This is because native Spark doesn't support it https://github.com/apache/spark/blob/c16a66a64bf9599b4fefcdc2beaad7c4f2a4517e/python/pyspark/sql/pandas/types.py#L89
