### ISSUE TITLE
[QUESTION] Full Spark Example

### ISSUE THREAD

**Issue by FedericoGarza** [fugue-project/fugue#325]
Hi! 

Congratulations on your great work.
I was wondering if you have a full example using a spark cluster, from launching the cluster (maybe using AWS) to running the `FugueWorkflow` on it.

**Comment by kvnkho** [comment]
As long as you can get a Spark session, you can do

```python
with FugueWorkflow(engine=spark) as dag:
    ....
```

For Databricks, you can install `databricks-connect` and your local SparkSession will activate the cluster and run the job on the cluster. Happy to give you a demo of that if you want. There is a sample of that [here](https://fugue-tutorials.readthedocs.io/tutorials/applications/databricks_connect.html#using-fugue-on-databricks)

For EMR, it is a bit harder as you'd have to use `spark-submit`. I am personally more experienced with Databricks (and can demo that for you if you want). My e-mail is in my Github profile. For EMR, I can look into that a bit and get back to you.

**Comment by goodwanghan** [comment]
Clsoing, feel free to reopen
