### ISSUE TITLE
[BUG] Aggregations on Spark dataframes fail intermittently

### ISSUE THREAD

**Issue by jstammers** [fugue-project/fugue#392]
**Minimal Code To Reproduce**

```python
from fugue import DataFrame, FugueWorkflow
from fugue.column import lit, col
import pandas as pd

def aggregate_prices(
    df: DataFrame,
    rollup: DataFrame,
) -> DataFrame:
    agg_order = [["a"], ["a", "b"], ["a","b", "c"]]
    agg_levels = [1,2,3]
    for i, (cols, gid) in enumerate(zip(agg_order, agg_levels)):
        levels = ",".join(cols)
        price = rollup.filter(col("group_id") == gid).select(
            *cols
            + [
                lit(levels).alias(f"level_{i}"),
            ]
        )
        df = df.join(price, how="left_outer", on=cols)
    return df

prices= pd.DataFrame({"a":[1,2,3], "b":[1,2,3], "c":[1,1,2], "price":[0.1,0.2,0.3], "group_id":[1,2,3]})
df = pd.DataFrame({"a": [1,1,2,3], "b":[1,2,3,4], "c":[1,2,3,4]})


dag = FugueWorkflow()
df_f  = dag.df(df)
prices_f = dag.df(prices)
agg = aggregate_prices(df_f, prices_f)
dag.run('spark')
```

**Describe the bug**
When running the above code, I intermittently encounter the following error
```
ERROR:root:_5 _State.RUNNING -> _State.FAILED  Table or view not found: _a2656; line 1 pos 14;
'Project [*]
+- 'Filter ('group_id = 2)
   +- 'UnresolvedRelation [_a2656], [], false

AnalysisException: Table or view not found: _a2656; line 1 pos 14;
'Project [*]
+- 'Filter ('group_id = 2)
   +- 'UnresolvedRelation [_a2656], [], false
```
I have observed this issue in a few of my pipelines. From what I have seen, the error seems to occur during inline transformations,
e.g.
```python
agg = df.filter(...).partition_by(...).aggregate(...)
```
**Expected behavior**
This transformation should execute without failing every time the workflow is run

**Environment (please complete the following information):**
 - Backend:  spark
 - Backend version: pyspark - 3.3.0
 - Python version: 3.9
 - OS: linux

**Comment by jstammers** [comment]
Hi, thanks for the reply. I will try persisting the dataframes and see if that resolves the issue.
I have just encountered the problem during the following 
```python
    449     df_f = dag.df(df)
    450     keys = df_f.select("CGAIdent", "SingleBuyProductItemId", "State").distinct()
--> 451     date_keys = df_f.select("USPeriod").distinct()
    452     keys = date_keys.join(dates_f, on=["USPeriod"], how="inner").join(keys, how="cross")
```
which I can't understand. If it helps, I am using the 11.4 DBR

**Comment by goodwanghan** [comment]
@jstammers I apologize for the delay. I have a theory how it happened. I am currently in a very big code change (almost finished) I will also include the fix, and if possible please help us test.

**Comment by goodwanghan** [comment]
Also if you want to iterate on notebook, you can run
```python
fa.set_global_engine(spark)
```
in a cell, and then you don't need to specify engine again.
