### ISSUE TITLE
[BUG] pandas string dtype is not recognised by fugue[dask]

### ISSUE THREAD

**Issue by rdmolony** [fugue-project/fugue#415]
Hey team,

You're probably aware of this one, raising in case slipped through the cracks ;)

**Minimal Code To Reproduce**

```python
from fugue.api import fugue_sql
import pandas as pd

example = pd.Series(["i_break_dask"], name="string_column", dtype="string").to_frame()
fugue_sql("SELECT * FROM example", engine="dask")
# /venv/lib/python3.7/site-packages/pyarrow/types.pxi in pyarrow.lib.from_numpy_dtype()
# TypeError: Cannot interpret 'string[python]' as a data type
```

**Describe the bug**
`pandas` `string` dtype is not recognised by `fugue`

**Expected behavior**
`string` columns are recognised as `fugue` `string` or `arrow` `string`

**Environment (please complete the following information):**
 - Backend: dask | fugue 0.8.0
 - Backend version: 2022.2.0
 - Python version: 3.7.12
 - OS: linux

I don't think `string` is yet the default behaviour for `pandas` `string` columns, if this ever becomes the case then this might become more of an issue

**Comment by goodwanghan** [comment]
I investigated, this is a bug. And it will be fixed in triad.

**Comment by goodwanghan** [comment]
Please upgrade triad to 0.8.1, it should solve this problem. Thanks for reporting.
