### ISSUE TITLE
[FEATURE] Print transpiled SQL query upon error

### ISSUE THREAD

**Issue by ttjoseph** [fugue-project/fugue#419]
With 0.8.x, FugueSQL now transpiles SQL queries, which naturally breaks code written against 0.7.x.

However error messages due to problems with the query are still those from the SQL backend. However we cannot see by default what is the transpiled query that was sent to the backend that caused the error. So it can be very difficult to diagnose problems, as the error message does not correspond to the query that was passed to Fugue.

The obvious solution would be to print the transpiled query upon exception, perhaps optionally, specified as a parameter to .run().

Thanks for your consideration.

**Comment by goodwanghan** [comment]
Great suggestion, I think we can log that as debug message, and you can enable debug messages to see the details?

**Comment by goodwanghan** [comment]
Also do you think a configuration to specify the default dialect will be helpful. As of now we can't fully support other dialects, but at least whatever you have now can be supported.

```python
fugue.sql.dialect
```

**Comment by ttjoseph** [comment]
With `fugue.sql.dialect` do you mean specify the `read` parameter to `sqlglot.transpile`? This way I could specify I am using DuckDB dialect in queries passed to fsql(). It would be a simple way to migrate to 0.8.x with minimal code change which would be really great.

I would be very happy to have the transpiled SQL available as a debug message behind a flag as you suggest.

Thank you!

**Comment by goodwanghan** [comment]
Ok will at least have the logging

**Comment by goodwanghan** [comment]
@ttjoseph i forgot to let you know that we already can control the query dialect in fugue. We may not support all syntax of all queries, but as long as it can be parsed by our antlr parser, it's fine. Our sql syntax is relatively tolerant for different dialects.

Here is how to do it globally.

```python
from fugue import register_global_conf

register_global_conf({"fugue.sql.compile.dialect":"duckdb"})
```

or you can just put that in your engine config.

**Comment by ttjoseph** [comment]
Thank you!On Feb 16, 2023, at 2:53 AM, Han Wang ***@***.***> wrote:﻿
@ttjoseph i forgot to let you know that we already can control the query dialect in fugue. We may not support all syntax of all queries, but as long as it can be parsed by our antlr parser, it's fine. Our sql syntax is relatively tolerant for different dialects.
Here is how to do it globally.
from fugue import register_global_conf

register_global_conf({"fugue.sql.compile.dialect":"duckdb"})
or you can just put that in your engine config.
