### ISSUE TITLE
[FEATURE] Consider adding polars backend/frontend?

### ISSUE THREAD

**Issue by ritchie46** [fugue-project/fugue#426]
Polars is a blazingly fast DataFrame with an API that is designed for parallelization and streaming data ( hinting at your blog: https://towardsdatascience.com/why-pandas-like-interfaces-are-sub-optimal-for-distributed-computing-322dacbce43)

Considered exposing it as frontend/backend? On a single machine it will run much faster than modin/spark/dask.

**Comment by goodwanghan** [comment]
@ritchie46 yes we are very interested in integrating with Polars. If you have like we can find a time to chat next week about this?

**Comment by ritchie46** [comment]
Yes, that'd be great. Which timezone are you on? I am on Amsterdam time. My email is ritchie46@gmail.com, we can fill out the details there.
