### ISSUE TITLE
[FEATURE] support for spark/databricks connect 

### ISSUE THREAD

**Issue by bitsofinfo** [fugue-project/fugue#464]
Been experimenting w/ fugue and databricks. My goal is to be able to programmatically alter the target databricks cluster/workspace as needed based on the various types of queries i'm running through fugue.

I've tried databricks-connect 11.3.x and this works fine w/ fugue `spark` as long as you have a `~/.databricks-connect` file with valid databricks endpoint configs... however this does not work well with the need to configure the connection programatically such as doing something like this (which does not work... the underlying config in ~/.databricks-connect` is still utilized.

```
  self.spark = SparkSession.builder.config("spark.databricks.service.address", "https://adb-xxx.18.azuredatabricks.net/?o=xx#folder/xx") \
                        .config("spark.databricks.service.token", "xx-x")  \
                        .config("spark.databricks.service.clusterId", "x-x-xx") \
                        .config("spark.databricks.service.orgId", "xx") \
                        .config("spark.databricks.service.port", "15001")  \
                        .config("spark.sql.execution.arrow.pyspark.enabled", "true") \
                    .getOrCreate()

fa.fugue_sql_flow(sql_flow_stmt).run(self.spark,self.engine_config)
```

Next I see that databricks-connect 13.x permits for programatic configuration of the spark session via ENV vars OR the `DatabricksSession` builder [as described here](https://docs.databricks.com/dev-tools/databricks-connect.html#set-up-the-client).  When i've tried something like this I get: `Fugue execution engine is not recognized (<pyspark.sql.connect.session.SparkSession object at 0x14c8924a0>, {'fugue.workflow.checkpoint.path': '/tmp/da-egress-service/results'}, {}). You may need to register a parser for it.`

```
from databricks.connect import DatabricksSession

spark = DatabricksSession.builder.remote(
  host       = "https://<workspace-instance-name>",
  token      = "<access-token-value>",
  cluster_id = "<cluster-id>"
).getOrCreate()

fa.fugue_sql_flow(sql_flow_stmt).run(self.spark,self.engine_config)
```

Next per @goodwanghan i tried registering an exec engine `register_execution_engine` using databricks-connect 13.0.0

```
from databricks.connect import DatabricksSession
from fugue.execution.factory import register_execution_engine
from fugue_spark import SparkExecutionEngine
from pyspark.sql.connect.session import SparkSession

register_execution_engine(SparkSession,lambda session, conf: SparkExecutionEngine(session, conf))

self.dbxsession = DatabricksSession.builder.remote(
    host       = "https://xxxx-xxxx.azuredatabricks.net/?o=xx#folder/xx",
    token      = "xxx",
    cluster_id = "xxxxxx"
).getOrCreate()

fa.fugue_sql_flow(sql_flow_stmt).run(self.dbxsession,self.engine_config)
```

However the `pyspark.sql.connect.session.SparkSession` doesn't implement `sparkContext()`: error: `sparkContext() is not implemented.`

https://github.com/apache/spark/blob/master/python/pyspark/sql/connect/session.py#L479

At this point this is getting beyond my comfort level/knowledge.

Appreciate the help and work on this project!

@goodwanghan @kvnkho for reference: https://fugue-project.slack.com/archives/C015RGNUW77/p1682529474759219

**Comment by kvnkho** [comment]
Thanks for writing this up! We need to update Fugue to be able the new version here. We'll do it in the next week or two.

**Comment by goodwanghan** [comment]
From 0.8.4.dev2, we started support spark connect.

If you are using Databricks 13.0+ you don't even need fugue-cloudprovider, just initialize your DatabricksSparkSession on your local env in the standard way, and that spark session can be recognized by Fugue as the spark execution engine.

**Comment by goodwanghan** [comment]
You need to understand Spark connect has these limitations by design:

https://docs.databricks.com/dev-tools/databricks-connect.html#pyspark-dataframe-api-limitations
https://docs.databricks.com/dev-tools/databricks-connect.html#databricks-and-databricks-connect-limitations
