### ISSUE TITLE
[BUG] can not import `fugue` on python 3.10

### ISSUE THREAD

**Issue by anirban-ray-publicis-sapient** [fugue-project/fugue#480]
**Minimal Code To Reproduce**

1. create a new python `3.10` environment
2. install `fugue` using `pip`

<details>

<summary> Result of `pip freeze`: </summary>

```
adagio==0.2.4
antlr4-python3-runtime==4.11.1
appdirs==1.4.4
fs==2.4.16
fugue==0.8.4
fugue-sql-antlr==0.1.6
Jinja2==3.1.2
MarkupSafe==2.1.3
numpy==1.24.3
pandas==2.0.2
pyarrow==12.0.0
python-dateutil==2.8.2
pytz==2023.3
qpd==0.4.2
six==1.16.0
sqlglot==15.0.0
triad==0.9.0
tzdata==2023.3
```

</details>

```python
import fugue
```

**Describe the bug**
Running `import fugue` leads to the following error:

> ModuleNotFoundError: No module named '_qpd_antlr'

<details>

<summary> Here is the full traceback: </summary>

```pycon
Python 3.10.11 (main, Apr 20 2023, 13:59:00) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fugue
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/venv/lib/python3.10/site-packages/fugue/__init__.py", line 5, in <module>
    from fugue.api import out_transform, transform
  File "/path/to/venv/lib/python3.10/site-packages/fugue/api.py", line 34, in <module>
    from .execution.api import (
  File "/path/to/venv/lib/python3.10/site-packages/fugue/execution/__init__.py", line 2, in <module>
    from .api import *
  File "/path/to/venv/lib/python3.10/site-packages/fugue/execution/api.py", line 17, in <module>
    from .factory import make_execution_engine, try_get_context_execution_engine
  File "/path/to/venv/lib/python3.10/site-packages/fugue/execution/factory.py", line 15, in <module>
    from .native_execution_engine import NativeExecutionEngine
  File "/path/to/venv/lib/python3.10/site-packages/fugue/execution/native_execution_engine.py", line 6, in <module>
    from qpd_pandas import run_sql_on_pandas
  File "/path/to/venv/lib/python3.10/site-packages/qpd_pandas/__init__.py", line 3, in <module>
    from qpd_pandas.engine import QPDPandasEngine, run_sql_on_pandas
  File "/path/to/venv/lib/python3.10/site-packages/qpd_pandas/engine.py", line 9, in <module>
    from qpd import QPDEngine, run_sql
  File "/path/to/venv/lib/python3.10/site-packages/qpd/__init__.py", line 6, in <module>
    from qpd.run import run_sql
  File "/path/to/venv/lib/python3.10/site-packages/qpd/run.py", line 3, in <module>
    from qpd._parser.sql import QPDSql
  File "/path/to/venv/lib/python3.10/site-packages/qpd/_parser/sql.py", line 6, in <module>
    from _qpd_antlr import QPDLexer, QPDParser
ModuleNotFoundError: No module named '_qpd_antlr'
>>> 
```

(`/path/to/venv` part is edited, rest is unchanged)

</details>

**Expected behavior**
No error.

**Environment (please complete the following information):**
 - Backend: pandas/dask/ray?
 - Backend version: 0.8.4
 - Python version: 3.10.11
 - OS: macOS Ventura

**Comment by kvnkho** [comment]
Hi @anirban-ray-publicis-sapient , sorry about that. We made a release last night on one of the dependencies and that seemed to have broken things. We have retracted the package so you should be able to just re-install Fugue and it should work.

**Comment by cmditch** [comment]
This still seems to be an issue. Unfortunately has caused all our code/jobs to fail today 😞 . 
Despite `qpd==0.4.2` being [yanked on pypi](https://pypi.org/project/qpd/#history), it's still being installed, which seems very odd given that it's.... yanked. lol.

It looks like `qpd` used to live on github and was maintained by @goodwanghan, but looks like the repo has since moved. Anyone know where this project lives now?

**Comment by kvnkho** [comment]
Oh sorry about that. I think you might need to do 

```
pip install  --no-cache-dir   ...
```

so that it doesn't used the cached wheels. We're about to push a real fix soon. We actually never open sourced qpd because we wanted to eventually deprecate it, but we still maintain it. If it persists, I'm happy to hop on a call.

**Comment by cmditch** [comment]
Ahh, thanks for the help and info @kvnkho !

**Comment by kvnkho** [comment]
Hey @anirban-ray-publicis-sapient, @cmditch 

The fix has been released. It was a packaging issue in qpd. Sorry about that! 

The working versions are:
* qpd >-= 0.4.3
* triad >= 0.9.0

Note that if you already have Fugue installed in the environment and you do:

```
pip install -U fugue
```

This may not upgrade those packages if Fugue does not upgrade. So it's much better to install these explicitly:

```
pip install -U qpd triad
```

Thanks for reporting the issue and sorry about that! Closing this issue for now but please feel free to ping us if there are other issues.

**Comment by anirban-ray-publicis-sapient** [comment]
Yes, the new version solves the problem for us. Thanks for the prompt fix, much appreciated.
