### ISSUE TITLE
[FEATURE] Use `_collect_as_arrow` for `fugue_api.as_arrow(spark_df)`

### ISSUE THREAD

**Issue by ion-elgreco** [fugue-project/fugue#516]
**Is your feature request related to a problem? Please describe.**
Convert spark df to arrow can be done with private method inside pyspark: `_collect_as_arrow` https://github.com/apache/spark/blob/06ccb6d434476afacc08936cf473670102d41010/python/pyspark/sql/pandas/conversion.py#L244

**Comment by goodwanghan** [comment]
This is a great idea, will release a dev version

**Comment by goodwanghan** [comment]
@ion-elgreco please try 0.8.7.dev5, it uses _collect_as_arrow

**Comment by ion-elgreco** [comment]
> @ion-elgreco please try 0.8.7.dev5, it uses _collect_as_arrow

Nice, I'll try it out later this week!
