### ISSUE TITLE
[BUG] There are some tests failing in Windows

### ISSUE THREAD

**Issue by kvnkho** [fugue-project/fugue#69]
**Minimal Code To Reproduce**

```
python3 -bb -m pytest tests/fugue
```

**Describe the bug**
On my system, the tests produced the following error:
```
FAILED tests/fugue/dataframe/test_utils.py::test_serialize_df - fs.errors.InvalidCharsInPath: path 'C:\Users\Kevin\AppData\Local\Temp\pytest-of-Kevin\pytest-5\test_serialize_df0\1.pkl' contains invalid characters
FAILED tests/fugue/execution/test_naive_execution_engine.py::NativeExecutionEngineTests::test_io - ValueError: invalid path C:\Users\Kevin\AppData\Local\Temp\pytest-of-Kevin\pytest-5\test_io0\a
FAILED tests/fugue/execution/test_naive_execution_engine.py::NativeExecutionEngineBuiltInTests::test_io - ValueError: invalid path C:\Users\Kevin\AppData\Local\Temp\pytest-of-Kevin\pytest-5\test_io1\a
FAILED tests/fugue/utils/test_io.py::test_parquet_io - ValueError: invalid path C:\Users\Kevin\AppData\Local\Temp\pytest-of-Kevin\pytest-5\test_parquet_io0\a.parquet
FAILED tests/fugue/utils/test_io.py::test_csv_io - ValueError: invalid path C:\Users\Kevin\AppData\Local\Temp\pytest-of-Kevin\pytest-5\test_csv_io0\a.csv
FAILED tests/fugue/utils/test_io.py::test_json - ValueError: invalid path C:\Users\Kevin\AppData\Local\Temp\pytest-of-Kevin\pytest-5\test_json0\a.json
```

**Expected behavior**
Tests should work despite the OS

**Environment (please complete the following information):**
 - Python version: 3.6.9
 - OS: Windows

**Comment by goodwanghan** [comment]
Great catch, let's see if we can modify the code to make them work on both Linux and Windows.

**Comment by kvnkho** [comment]
The issue here is that pytest creates a path like:
```
 C:\Users\kkho\AppData\Local\Temp\pytest-of-KKho\pytest-10\test_json0\a.json
```

The `save_df` function uses triad FileSystem, which uses _FSPath. _FSPath does not seem friendly towards Windows paths. To replicate:
```
_FSPath('C:/Users/kkho/')
```
gives an error
```
ValueError: invalid path C:/Users/Kkho
```

Looking at the code for triad:

```python
        path = self._modify_path(path)
        if path.startswith("file://"):
            path = path[6:]
        if path.startswith("/"):
            self._scheme = ""
            self._root = "/"
            self._path = os.path.abspath(path)
        else:
            uri = urlparse(path)
```
Windows paths will go to the else because of the way they are formatted ('C:/Users/kkho/...'). _modify_path does not catch this. Changing the path to Pathlib in the unit test also does not work here because urlparse does not work with Pathlib. To test:

```python
import pathlib
pathlib.Path.cwd()
urlparse(pathlib.Path.cwd())
```
This gives:
```
AttributeError: 'WindowsPath' object has no attribute 'decode'
```

My suggestion here is to modify the _FSPath to support Windows paths. We might be able to do this by putting the logic in the _modify_path method. Should we close the issue in this repo and move it to triad? What are your thoughts?

**Comment by kvnkho** [comment]
Close this issue for now. There were some fixes applied in the triad repo. There are still some failing tests, but fixing them requires a bigger refactor on the triad side, potentially around Pathlib.

**Comment by kvnkho** [comment]
Close this issue for now. There were some fixes applied in the triad repo. There are still some failing tests, but fixing them requires a bigger refactor on the triad side, potentially around Pathlib.
