### ISSUE TITLE
[BUG] LIKE '{%' conflicts with jinja template

### ISSUE THREAD

**Issue by goodwanghan** [fugue-project/fugue#76]
**Minimal Code To Reproduce**

```sql
CREATE [["x"]] SCHEMA a:str
SELECT * WHERE a LIKE '{%'
PRINT
```

**Describe the bug**
Jinja thinks `{%` is a partial template sign, a syntax error

**Expected behavior**
It should work

**Environment (please complete the following information):**
 - Backend: pandas/dask/ray? spark
 - Backend version: spark 3
 - Python version: 3.6.9
 - OS: linux/windows linux

**Comment by WangCHX** [comment]
Posted a fix. https://github.com/fugue-project/fugue/pull/85 but not sure if it is the safest.
