### ISSUE TITLE
[FEATURE] presort should also take array as input

### ISSUE THREAD

**Issue by goodwanghan** [fugue-project/fugue#79]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
https://github.com/fugue-project/fugue/blob/d60493cf33acd5460031b1a4fa53da71036df031/fugue/collections/partition.py#L217

Currently, presort can only be string expression, but programming should also be able to use arrays

`"a,b"` == `["a", "b"]` == `[("a", True),("b", True)]`
`"a desc,b"` == `[("a", False), "b"]` == `[("a", False),("b", True)]`

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by WangCHX** [comment]
link PR: https://github.com/fugue-project/fugue/pull/86
